### ISSUE TITLE
Explicitly Defined uid and gid for service_user

### ISSUE THREAD

**Issue by JoelProminic** [STARTcloud/startcloud_roles#2]
While testing the Moonshine-dev 1.5.0 release, we ran into an problem where the fileshares were owned by the wrong user. The GCR configuration defined the expected user and group by ID using `mountOptions`:

```
     volumes:
     - name: local
       csi:
         driver: gcsfuse.run.googleapis.com
         volumeAttributes:
           bucketName: moonshine.dev
           mountOptions: uid=994,gid=994,rename-dir-limit=4096
```

It looks like the provisioners are not enforcing a static user or group ID, so this is going to depend on the order of the actions:

https://github.com/STARTcloud/startcloud_roles/blob/eb47679f55b6038370184fce13a6f34fc627cb3d/roles/service_user/tasks/main.yml#L21-L56

I see parameters to set the [uid](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html#parameter-uid) and [gid](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/group_module.html#return-gid) so that we can enforce this.  I think `service_user` is the only external case where the uid and gid matter, but we may want to set the others to avoid collisions.  The uid and gid should be set as vars so that they can be overwritten in the moonshine-dev configuration if needed.
